import Link from "next/link";
import Image from "next/image";
import { db } from "@/lib/db";
import { cache } from "react";
import { AdsterraBanner, AdsterraNative } from "@/components/AdsterraAds";

interface Props { params: Promise<{ slug: string }> }
export const revalidate = 60;
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://hindi-news-omega.vercel.app").replace(/\/$/, "");

const getCategory = cache(async (slug: string) => db.category.findUnique({ where: { slug }, select: { id: true, name: true, slug: true, description: true, news: { where: { status: "PUBLISHED" }, orderBy: { publishedAt: "desc" }, take: 30, select: { id: true, title: true, description: true, imageUrl: true, sourceName: true, publishedAt: true, createdAt: true } } } }));

const FLOW: Record<string, { intro: string; audience: string; steps: string[]; related: { slug: string; label: string }[] }> = {
  jobs: { intro: "सरकारी भर्ती की जानकारी को सिर्फ पढ़ें नहीं—आवेदन से लेकर रिजल्ट तक अगला काम समझें।", audience: "जो उम्मीदवार भर्ती की पात्रता, आवेदन, परीक्षा और परिणाम की प्रक्रिया समझना चाहते हैं।", steps: ["Official भर्ती नोटिस देखें", "पात्रता और जरूरी दस्तावेज verify करें", "OTR/आवेदन पूरा करें", "Admit Card मिलने पर डाउनलोड करके विवरण जांचें", "परीक्षा के बाद Answer Key/आपत्ति देखें", "Official Result और अगला चरण देखें"], related: [{ slug: "admit-card", label: "Admit Card" }, { slug: "results", label: "Results" }, { slug: "answer-key", label: "Answer Key" }] },
  exams: { intro: "परीक्षा से जुड़े अपडेट में आपको अगला काम, जरूरी दस्तावेज और official action साफ मिलेगा।", audience: "परीक्षा की तैयारी, आवेदन, प्रवेश-पत्र, परीक्षा और परिणाम से जुड़े विद्यार्थियों के लिए।", steps: ["Official परीक्षा सूचना पढ़ें", "Syllabus/पात्रता और आवेदन की शर्तें verify करें", "Application status जांचें", "Admit Card आने पर details verify करें", "Exam instructions देखें", "Answer Key और Result के अगले चरण पर जाएं"], related: [{ slug: "jobs", label: "सरकारी भर्ती" }, { slug: "admit-card", label: "Admit Card" }, { slug: "results", label: "Results" }] },
  "admit-card": { intro: "Admit Card मिला है तो सिर्फ PDF खोलना पर्याप्त नहीं—नाम, रोल नंबर, परीक्षा केंद्र और निर्देश भी जांचें।", audience: "जिन उम्मीदवारों की परीक्षा नजदीक है या जिनका प्रवेश-पत्र जारी हो चुका है।", steps: ["Official Admit Card link खोलें", "Application/SSO details से डाउनलोड करें", "नाम, रोल नंबर और परीक्षा केंद्र जांचें", "फोटो/हस्ताक्षर और निर्देश देखें", "Exam date/time और reporting instructions official notice से मिलाएं", "परीक्षा के बाद Answer Key/Result देखें"], related: [{ slug: "exams", label: "परीक्षाएं" }, { slug: "answer-key", label: "Answer Key" }, { slug: "results", label: "Results" }] },
  "answer-key": { intro: "Answer Key आने के बाद अपने उत्तर मिलाएं और यदि official objection window हो तो उसी प्रक्रिया का उपयोग करें।", audience: "परीक्षा दे चुके उम्मीदवारों के लिए।", steps: ["Official Answer Key डाउनलोड करें", "अपने उत्तरों का मिलान करें", "Question/Answer में समस्या हो तो official objection instructions देखें", "Objection window और नियम official notice से verify करें", "Final Answer Key/Result के अगले अपडेट पर नजर रखें"], related: [{ slug: "admit-card", label: "Admit Card" }, { slug: "results", label: "Results" }, { slug: "exams", label: "परीक्षाएं" }] },
  results: { intro: "Result को सिर्फ score की तरह नहीं देखें—official result के बाद आपका अगला चरण क्या है, यह भी समझें।", audience: "परीक्षा/भर्ती का परिणाम देखने वाले उम्मीदवारों के लिए।", steps: ["Official Result portal खोलें", "Application/Roll Number और जन्मतिथि जैसी मांगी गई जानकारी भरें", "Result/scorecard डाउनलोड या सुरक्षित करें", "यदि official merit/cutoff/shortlist है तो उसे verify करें", "Document verification/अगले चरण की official सूचना देखें"], related: [{ slug: "jobs", label: "सरकारी भर्ती" }, { slug: "answer-key", label: "Answer Key" }, { slug: "admit-card", label: "Admit Card" }] },
  scholarship: { intro: "छात्रवृत्ति में सबसे जरूरी है सही session, eligibility, OTR, documents, application और verification को क्रम से पूरा करना।", audience: "स्कूल, कॉलेज और उच्च शिक्षा के विद्यार्थियों के लिए जो scholarship के लिए आवेदन या status देखना चाहते हैं।", steps: ["Official scholarship/scheme और session verify करें", "जहां OTR जरूरी हो वहां OTR पूरा करें", "Income, domicile, marksheet, admission और bank details जैसे मांगे गए documents तैयार रखें", "Online application भरकर details दोबारा जांचें", "Institute/department verification की स्थिति देखें", "Application status/payment की official स्थिति जांचें"], related: [{ slug: "schemes", label: "सरकारी योजनाएं" }, { slug: "documents", label: "Documents" }, { slug: "admission", label: "Admissions" }] },
  admission: { intro: "Admission update का मतलब सिर्फ form भरना नहीं है—eligibility, documents, counselling और final admission तक पूरा flow समझें।", audience: "स्कूल, कॉलेज और अन्य शैक्षणिक प्रवेश प्रक्रिया से जुड़े विद्यार्थियों के लिए।", steps: ["Official admission notice पढ़ें", "Eligibility और course/seat conditions verify करें", "Application form और जरूरी documents तैयार करें", "Application status/merit/counselling update देखें", "Verification या counselling की सूचना follow करें", "Final admission/fee/document submission की official instruction देखें"], related: [{ slug: "documents", label: "Documents" }, { slug: "scholarship", label: "Scholarship" }, { slug: "exams", label: "परीक्षाएं" }] },
  documents: { intro: "किस काम के लिए कौन सा document चाहिए, उसे official requirement से मिलाकर तैयार करें—अनुमान से नहीं।", audience: "Admission, scholarship, recruitment और सरकारी student services के लिए documents तैयार करने वाले विद्यार्थियों के लिए।", steps: ["जिस काम के लिए document चाहिए उसकी official requirement देखें", "Original document और valid copy/scan तैयार रखें", "नाम, जन्मतिथि और अन्य details में mismatch जांचें", "जहां जरूरी हो DigiLocker/e-Vault/official record से verify करें", "Application में document सही जगह upload/submit करें"], related: [{ slug: "jobs", label: "सरकारी भर्ती" }, { slug: "scholarship", label: "Scholarship" }, { slug: "admission", label: "Admissions" }] },
  schemes: { intro: "सरकारी योजना में सबसे पहले यह पता करें कि आप उस scheme की official eligibility में आते हैं या नहीं और आवेदन कहां होता है।", audience: "विद्यार्थियों और परिवारों के लिए जो education/student benefit schemes की जानकारी चाहते हैं।", steps: ["Official scheme और विभाग पहचानें", "Class/category/gender/income जैसी लागू conditions verify करें", "Required documents देखें", "Official application route से आवेदन करें", "Application/status/verification की स्थिति देखें"], related: [{ slug: "scholarship", label: "Scholarship" }, { slug: "documents", label: "Documents" }, { slug: "admission", label: "Admissions" }] },
  "current-affairs": { intro: "Current Affairs को सिर्फ पढ़ने के बजाय उन updates को पहचानें जो exam, भर्ती, scholarship और student work में काम आते हैं।", audience: "प्रतियोगी परीक्षाओं और सामान्य अध्ययन की तैयारी करने वाले विद्यार्थियों के लिए।", steps: ["Student-useful update चुनें", "Official source से fact verify करें", "Exam/भर्ती से उसका संबंध समझें", "जरूरी point नोट करें", "जहां कोई official action है वहां संबंधित task page पर जाएं"], related: [{ slug: "exams", label: "परीक्षाएं" }, { slug: "jobs", label: "सरकारी भर्ती" }, { slug: "scholarship", label: "Scholarship" }] }
};

function flowFor(slug: string, name: string) { return FLOW[slug] || { intro: `${name} से जुड़ी जानकारी को समझने के साथ यह भी देखें कि official तौर पर आपको अगला क्या काम करना है।`, audience: `${name} से जुड़ी student information खोजने वाले पाठकों के लिए।`, steps: ["Official update/source पहचानें", "Eligibility और लागू शर्तें verify करें", "जरूरी documents/details तैयार करें", "Official action या application करें", "Status/अगले चरण की सूचना जांचें"], related: [{ slug: "jobs", label: "सरकारी भर्ती" }, { slug: "scholarship", label: "Scholarship" }, { slug: "results", label: "Results" }] }; }

export async function generateMetadata({ params }: Props) { const { slug } = await params; const category = await getCategory(slug); if (!category) return { title: "कैटेगरी नहीं मिली", robots: { index: false, follow: true } }; const flow = flowFor(slug, category.name); const description = `${category.name}: ${flow.intro}`.slice(0, 160); return { title: `${category.name} | छात्र के काम की आधिकारिक जानकारी`, description, robots: { index: true, follow: true }, alternates: { canonical: `${SITE_URL}/category/${category.slug}` }, openGraph: { type: "website", title: `${category.name} | छात्र के काम की आधिकारिक जानकारी`, description, url: `${SITE_URL}/category/${category.slug}` }, twitter: { card: "summary", title: `${category.name} | छात्र के काम की आधिकारिक जानकारी`, description } }; }

export default async function CategoryPage({ params }: Props) {
  const { slug } = await params; const category = await getCategory(slug);
  if (!category) return <main className="container mx-auto px-4 py-16 text-center"><h1 className="mb-2 text-2xl font-bold text-red-600">कैटेगरी नहीं मिली</h1><p className="mb-6 text-gray-600">यह student information category अभी उपलब्ध नहीं है।</p><Link href="/" prefetch className="inline-block rounded-md bg-red-600 px-5 py-2 font-medium text-white">Student Home पर जाएं</Link></main>;
  const flow = flowFor(slug, category.name);
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "होम", item: SITE_URL }, { "@type": "ListItem", position: 2, name: category.name, item: `${SITE_URL}/category/${category.slug}` }] };
  return <main className="container mx-auto max-w-5xl px-4 py-6"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    <section className="rounded-3xl bg-gradient-to-br from-red-700 to-red-500 p-6 text-white shadow-lg sm:p-8"><div className="mb-2 text-sm font-bold opacity-90">Student Action Center</div><h1 className="text-3xl font-black sm:text-4xl">{category.name}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-red-50 sm:text-base">{flow.intro}</p><div className="mt-5 rounded-2xl bg-white/10 p-4 text-sm leading-6"><b>किसके लिए?</b> {flow.audience}</div></section>
    <section className="mt-6 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-gray-900">इस category में आपका काम कैसे आगे बढ़ेगा?</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{flow.steps.map((step, i) => <div key={step} className="flex gap-3 rounded-xl border border-gray-100 bg-gray-50 p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-red-600 text-sm font-black text-white">{i + 1}</span><p className="text-sm font-semibold leading-6 text-gray-800">{step}</p></div>)}</div></section>
    <AdsterraNative />
    <section className="mt-6"><div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-red-600">Official-first updates</p><h2 className="text-2xl font-black text-gray-900">इस category की नई जानकारी</h2></div><span className="text-xs text-gray-500">{category.news.length} updates</span></div>{category.news.length === 0 ? <div className="rounded-2xl border border-dashed border-gray-300 bg-white py-16 text-center text-gray-500">अभी कोई नया update उपलब्ध नहीं है।</div> : <div className="grid gap-5 md:grid-cols-2">{category.news.map((item, index) => <article key={item.id} className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><Link href={`/news/${item.id}`} prefetch className="block" aria-label={`${item.title} का पूरा काम देखें`}>{item.imageUrl && <div className="relative h-48 w-full overflow-hidden bg-gray-100"><Image src={item.imageUrl} alt={item.title} fill sizes="(max-width: 768px) 100vw, 50vw" priority={index < 2} className="object-cover" /></div>}</Link><div className="p-5"><div className="mb-2 flex items-center justify-between gap-3 text-xs"><span className="font-bold text-red-600">{category.name}</span><span className="text-gray-400">{new Date(item.publishedAt || item.createdAt).toLocaleDateString("hi-IN", { day: "numeric", month: "short", year: "numeric" })}</span></div><Link href={`/news/${item.id}`} prefetch><h3 className="text-lg font-black leading-snug text-gray-950 hover:text-red-600">{item.title}</h3></Link><p className="mt-2 line-clamp-3 text-sm leading-6 text-gray-600">{item.description || "इस update में official जानकारी और आपके लिए अगला काम समझाया गया है।"}</p><div className="mt-4 flex items-center justify-between gap-3 border-t border-gray-100 pt-4"><span className="truncate text-xs text-gray-500">Official: {item.sourceName || "Source"}</span><Link href={`/news/${item.id}`} prefetch className="inline-flex min-h-10 shrink-0 items-center rounded-lg bg-red-600 px-4 py-2 text-xs font-bold text-white hover:bg-red-700">पूरा काम देखें →</Link></div></div></article>)}</div>}</section>
    <AdsterraBanner />
    <section className="mt-8 rounded-2xl border border-red-100 bg-red-50 p-5"><h2 className="text-xl font-black text-gray-900">अगला काम भी यहीं देखें</h2><p className="mt-2 text-sm leading-6 text-gray-700">एक student task पूरा होने के बाद अगला चरण अक्सर दूसरी category में आता है। जरूरत के हिसाब से आगे बढ़ें:</p><div className="mt-4 flex flex-wrap gap-2">{flow.related.map((r) => <Link key={r.slug} href={`/category/${r.slug}`} prefetch className="rounded-full bg-white px-4 py-2 text-sm font-bold text-red-700 shadow-sm hover:bg-red-600 hover:text-white">{r.label} →</Link>)}</div></section>
    <section className="mt-6 rounded-2xl border border-gray-200 bg-white p-5"><h2 className="text-lg font-black">हमारी जानकारी का नियम</h2><p className="mt-2 text-sm leading-6 text-gray-600">हम official source को आधार मानकर आसान Hindi में original explanation और action steps देते हैं। Date, fee, vacancy, eligibility या benefit जैसी जानकारी official source में न हो तो उसे अनुमान से नहीं जोड़ा जाता।</p><Link href="/search" prefetch className="mt-4 inline-flex rounded-lg bg-gray-900 px-4 py-2 text-sm font-bold text-white">अपना student काम खोजें →</Link></section>
  </main>;
}
